### ISSUE TITLE
Toggle panning

### ISSUE THREAD

**Issue by Dayonel** [emilefokkema/infinite-canvas#24]
Hi, first, thank you for this awesome work.

Not really an issue, but a question: is there any way to toggle enable/disable the panning?
In some cases, I need the click to perform other actions.

What I have tried so far (didn't work):
`infCanvas.addEventListener("mousedown", e => {
	e.preventDefault();
});`

**Comment by emilefokkema** [comment]
Thank you. As for your question: it so happens that I'm working on exactly that right now. So stay tuned :)

**Comment by fatihozdil** [comment]
@emilefokkema  are there any updates? toggling feature is what I need right now.

**Comment by emilefokkema** [comment]
working on it! the branch is [`mouse-events`](https://github.com/emilefokkema/infinite-canvas/tree/mouse-events). (But touch events will also enter the picture.) The interface will be almost the same as what @Dayonel described, the only difference being that the events emitted by an InfiniteCanvas will have a method

```ts
preventDefault(preventNativeDefault?: boolean): void
```
where the optional parameter `preventNativeDefault` will also prevent the default for the native event (the event emitted by the underlying `<canvas>` element). This will allow you to cancel zooming (which is InfiniteCanvas's default behavior on a `wheel` event) and also cancel scrolling.

**Comment by emilefokkema** [comment]
@fatihozdil @Dayonel In the meantime, here's a workaround (which I only realised just now):

```js
// suppose this is your canvas element
var canvasEl = document.getElementById('canvas');

// now, before you create the infinite canvas, you register an event handler for the mousedown event in the capturing phase:
canvasEl.addEventListener(
    'mousedown',
    (ev) => {
        // this prevents InfiniteCanvas's 'mousedown' event handler from being called, because that one will be attached to the
        // bubbling phase
        ev.stopPropagation();
    },
    // true meaning that this event handler will be called before the 'mousedown' event's bubbling phase
    true);

// and now create the infinite canvas
var infCanvas = new InfiniteCanvas(canvasEl);
```

**Edit**: come to think of it, it should not matter whether this 'capturing' event handler is registered before or after the creation of the InfiniteCanvas. In both cases, it will stop the event from reaching InfiniteCanvas's 'mousedown' event handler.

**Comment by emilefokkema** [comment]
@fatihozdil @Dayonel It's done: in [0.6.0-alpha](https://github.com/emilefokkema/infinite-canvas/releases/tag/v0.6.0-alpha) you can now call `preventDefault()` on a `mousedown` event that is emitted by the `InfiniteCanvas` and the `InfiniteCanvas` will not pan.

**Comment by Dayonel** [comment]
Thank you!!
