### ISSUE TITLE
Access to coordinate / zoom state (Question)

### ISSUE THREAD

**Issue by stormsson** [emilefokkema/infinite-canvas#27]
Hello, first of all thank you for your effort.

Is there a way to read the current coordinate state ?
Like the current zoom/scale state, or the local coordinates after panning?

Thank you

**Comment by emilefokkema** [comment]
@stormsson The current coordinate state can be read from the 'draw' event:
```js
infCanvas.addEventListener('draw', e => {
    // this is the transformation that transforms a point in the coordinates of the <canvas> element to a point
    // in InfiniteCanvas's coordinates
    const transformation = e.transformation;
    // and this is its inverse
    const inverseTransformation = e.inverseTransformation;
})
```
The same properties are present on the `transformationStart`, `transformationChange` and `transformationEnd` events. The transformations are given in the form of objects that have properties `a`, `b`, `c`, `d`, `e` and `f`, all of them numbers.  They have the same meaning as the corresponding parameters in for example the [`transform`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/transform) method on the canvas interface.

**Comment by stormsson** [comment]
Thank you!
