### ISSUE TITLE
Question: how can I pan the canvas?

### ISSUE THREAD

**Issue by qjack001** [emilefokkema/infinite-canvas#35]
I am looking for a way to programatically move around the canvas, so I can implement moving with arrow keys, etc. Is there a way to do this?

**Comment by emilefokkema** [comment]
The `InfiniteCanvas` only pans in response to events (coming from the underlying `<canvas>`) that indicate gestures that originate from a mouse or a touch. So I guess you could make `InfiniteCanvas` think such a thing is happening by [dispatching](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/dispatchEvent) fake events to the underlying `<canvas>`. I haven't tried this, so I can't promise it'll work correctly. If you try it, keep in mind that `InfiniteCanvas` [looks for](https://github.com/emilefokkema/infinite-canvas/blob/efa8f042b08b2da482202a48123f5962532fc80a/src/events/event-collections/handled-or-filtered-event-collection.ts#L100) both a [`mousedown`](https://developer.mozilla.org/en-US/docs/Web/API/Element/mousedown_event) _and_ a [`pointerdown`](https://developer.mozilla.org/en-US/docs/Web/API/Element/pointerdown_event) event in case of a gesture coming from a mouse.

Currently I have no plans to add support for doing this in an actually programmatic way.

**Comment by qjack001** [comment]
Thanks for the quick and detailed response Emile; I appreciate it. I'll look into your suggestion.
