### ISSUE TITLE
Dummy question

### ISSUE THREAD

**Issue by Colir** [emilefokkema/infinite-canvas#38]
Hi, before digging into your project, I have got a simple question :
Does it allow the use of images to create an infinite draw like the app Endless Paper (https://endlesspaper.app/)?
Thank you

**Comment by emilefokkema** [comment]
I don't know exactly what you mean, but `InfiniteCanvas` does support the [`drawImage()`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage) method, yes.
