### ISSUE TITLE
Missing types, or types incorrectly exported?

### ISSUE THREAD

**Issue by iaremarkus** [emilefokkema/infinite-canvas#44]
Hello :) 

Any tips on how the issue below could be resolved?

![pic-004165](https://github.com/emilefokkema/infinite-canvas/assets/936966/af667e17-7b24-45dc-98c7-7a42854138ad)

Seems perhaps the typings have not been correctly exported, and there's no typing defined at `bun add @types/ef-infinite-canvas` either :/ 

Hope you can assist 🙏
Thanks for your work on this
🤜🤛

**Comment by emilefokkema** [comment]
Do you have a minimal reproduction for me, in the form of a project with a package.json, a tsconfig.json etc.?

**Comment by emilefokkema** [comment]
@iaremarkus ?

**Comment by iaremarkus** [comment]
Apologies for the delay @emilefokkema. Life 😢

Give me 10mins, I'll make a repo :)

**Comment by iaremarkus** [comment]
@emilefokkema nothing fancy really. It happens right out of the box on a `create-next-app` app. I created a [repo](https://github.com/iaremarkus/infinite-canvas-test).

**Comment by emilefokkema** [comment]
Thanks! Just found a reproduction myself. In fact, I just released v0.6.4 :)

**Comment by emilefokkema** [comment]
@iaremarkus please let me know whether this issue still occurs with v0.6.4 of ef-infinite-canvas

**Comment by iaremarkus** [comment]
Hmm.. problem seems to remain for me. I restarted TS Server (and VSCode just to be safe), but with `0.6.4` it seems still to be unhappy with the types? 🤔

![pic-004287](https://github.com/emilefokkema/infinite-canvas/assets/936966/843249a6-a639-4145-b9b4-787b601197a9)

**Comment by emilefokkema** [comment]
Are you sure you now have 0.6.4 in your node_modules?

**Comment by emilefokkema** [comment]
I just checked out the reproduction repo, ran npm install (which installed 0.6.4) and everything was fine

**Comment by iaremarkus** [comment]
I'd done the upgrade with `ncu -u`, but after `bun remove` and `bun add`'ing again, it seems to have done the trick and the TS overlords seem happy.

Thanks @emilefokkema  🙌
Enjoy the weekend 🤜🤛
